"""Regenerate the manuscript's figure data files from the archived artifacts.

The manuscript plots no hand-entered numbers. Every point in the generated
figures is derived here, deterministically, from the SHA-256-manifested
artifacts under ``artifacts/``; ``scripts/verify_artifacts.py`` independently
establishes that those inputs are byte-exact.

Usage
-----
    python scripts/make_figures.py            # rewrite src/figures/*.dat
    python scripts/make_figures.py --check    # fail if committed data is stale

The ``--check`` mode runs in CI so that a figure can never silently drift away
from the evidence it claims to display.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "artifacts"
FIGURES = ROOT / "src" / "figures"

# Execution contexts in the order they are argued in the appendix: exact
# reference, independent-SDK ideal sampling, calibrated-noise simulation,
# physical device. The label is the plot's x-axis tick.
HARDWARE_RUNS = [
    ("aer", "Aer, ideal sampling"),
    ("fake_faketorino", "calibrated noise, torino snapshot"),
    ("hardware_ibm_kingston", "physical device, ibm_kingston"),
]

HEADER = (
    "# Generated by scripts/make_figures.py from the archived artifacts.\n"
    "# Do not edit by hand; run `python scripts/make_figures.py` instead.\n"
)


def _fmt(value: float) -> str:
    return f"{value:.6f}"


def build_hardware_table() -> str:
    """Energy estimate and shot-noise standard error per execution context."""
    lines = [HEADER]
    for position, (directory, label) in enumerate(HARDWARE_RUNS, start=1):
        lines.append(f"# index {position}: {label} (artifacts/hardware/{directory}/)\n")
    lines.append("index ehat stderr eref\n")
    for position, (directory, _label) in enumerate(HARDWARE_RUNS, start=1):
        manifest = json.loads(
            (ARTIFACTS / "hardware" / directory / "manifest.json").read_text(
                encoding="utf-8"
            )
        )
        results = manifest["results"]
        lines.append(
            "{index} {ehat} {stderr} {eref}\n".format(
                index=position,
                ehat=_fmt(results["E_hat"]),
                stderr=_fmt(results["E_stderr"]),
                eref=_fmt(results["E_ref_oracle"]),
            )
        )
    return "".join(lines)


def build_scale_table() -> str:
    """Wall-clock cost of each classical and simulated path against chain length."""
    sweep = json.loads((ARTIFACTS / "scale" / "sweep.json").read_text(encoding="utf-8"))
    lines = [HEADER, "n freefermion exactdiag statevector aer4096\n"]
    for row in sweep:
        exact = row.get("t_exact_diag_s")
        lines.append(
            "{n} {ff} {ed} {sv} {aer}\n".format(
                n=row["n"],
                ff=_fmt(row["t_free_fermion_s"]),
                ed=_fmt(exact) if exact is not None else "nan",
                sv=_fmt(row["t_statevector_s"]),
                aer=_fmt(row["t_aer_4096shots_s"]),
            )
        )
    return "".join(lines)


TABLES = {
    "hardware-energies.dat": build_hardware_table,
    "scale-timings.dat": build_scale_table,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed data files match the archived artifacts",
    )
    args = parser.parse_args()

    FIGURES.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name, builder in TABLES.items():
        target = FIGURES / name
        content = builder()
        if args.check:
            current = (
                target.read_text(encoding="utf-8") if target.exists() else ""
            )
            status = "OK " if current == content else "STALE"
            if current != content:
                stale.append(name)
            print(f"[{status}] src/figures/{name}")
        else:
            target.write_text(content, encoding="utf-8", newline="\n")
            print(f"[written] src/figures/{name}")

    if stale:
        print(
            "\nFigure data is stale with respect to artifacts/: "
            + ", ".join(stale)
            + "\nRun: python scripts/make_figures.py"
        )
        return 1

    print("\nFigure data is consistent with the archived artifacts.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
